ALL: server client
server: Driver.c
    @echo Compiling Server Build. . .
    @echo Successfully Compiled Build!
client: Driver.c
    @echo Compiling Client Build. . .
    @echo Successfully Compiled Build!
clean:
    @echo Thrashing Compiled Builds. . .
    @echo Successfully Expunged Binary Builds!
